@echo off
echo Initializing Git...
git init
echo Adding remote...
git remote add origin https://github.com/apk3206/Khedut-Bandhu.git
echo Staging files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Pushing...
git push -u origin main
