@echo off
echo Cleaning up sub-repos...
if exist d:\frontend\my-app\.git (
    attrib -h -r -s d:\frontend\my-app\.git /s /d
    rmdir /s /q d:\frontend\my-app\.git
)
cd /d d:\frontend
echo Initializing root repo...
git init
echo Adding remote...
git remote add origin https://github.com/apk3206/Khedut-Bandhu.git
echo Adding files...
git add .
echo Committing...
git commit -m "Initial monorepo commit"
echo Pushing...
git push -u origin main
